# Generated by Django 3.0.3 on 2021-01-09 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='gallery_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery'),
        ),
    ]
