# Generated by Django 3.0.3 on 2021-01-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_gallery_view_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='view_choices',
            field=models.CharField(choices=[('alt', 'alternating'), ('notalt', 'not-alternating')], default='alt', max_length=10),
        ),
    ]
