# Generated by Django 3.0.3 on 2021-01-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20210109_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='gallery_id',
            new_name='gallery',
        ),
        migrations.AddField(
            model_name='gallery',
            name='credits',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
