# Generated by Django 3.0.3 on 2021-01-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20210126_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='view_choices',
            new_name='layout',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.AddField(
            model_name='image',
            name='credits',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='index',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterOrderWithRespectTo(
            name='image',
            order_with_respect_to='index',
        ),
    ]
