# Generated by Django 3.0.3 on 2021-03-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0006_auto_20210225_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('center-photo', 'center-photo'), ('alt-photo', 'alt-photo')], default='alt-photo', max_length=12),
        ),
    ]
