# Generated by Django 3.0.3 on 2021-04-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0007_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='credits',
            field=models.TextField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
