# Generated by Django 3.0.3 on 2021-04-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0009_auto_20210420_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('center-photo', 'center-photo'), ('alt-photo', 'alt-photo'), ('big-centered-photo', 'big-centered-photo')], default='alt-photo', max_length=18),
        ),
    ]
