version: "3"
services:
  nginx:
    image: nginx-simple:latest
    container_name: nginx-simple
    restart: always
    network_mode: "bridge"
    volumes:
      - ./wwwroot/:/var/www/
    ports:
      - "8000:80"
    build:
      context: .
      