version: "3"
services:
  web:
    image: nginx-arch:latest
    volumes:
      - ./:/var/www/
    ports:
      - "8000:80"
    env_file: .env
    depends_on:
      - db
    build:
      context: .
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  
